name: lint

on:
  workflow_dispatch:
  push:
    branches-ignore:
      # Do not push events to branches matching refs/heads/main
      - 'main'
    tags-ignore: [ '*' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Run Revive Action
        uses: docker://morphy/revive-action:v2
        with:
          # Path to your Revive config within the repo (optional)
          config: revive/config.toml



